In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
%matplotlib inline

We're ready to build our first neural network. We will have multiple features we feed into our model, each of which will go through a set of perceptron models to arrive at a response which will be trained to our output.

Like many models we've covered, this can be used as both a regression or classification model.

First, we need to load our dataset. For this example we'll use The Museum of Modern Art in New York's [public dataset](https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv) on their collection.

In [ ]:
artworks = pd.read_csv('https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv')

In [4]:
#reducing the dataset to a sample for computational purposes

artworks = artworks.sample(frac = 0.1, replace=True, random_state = 108)

In [6]:
artworks.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ThumbnailURL',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='object')

We'll also do a bit of data processing and cleaning, selecting columns of interest and converting URL's to booleans indicating whether they are present.

In [7]:
# Select Columns.
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

In [8]:
artworks.head()

Artist  Nationality    Gender           Date  \
127075                 Rebecca Horn     (German)  (Female)           1998   
43467             Alfred Capel Cure    (British)    (Male)           1856   
46446                   Paul Strand   (American)    (Male)           1916   
127830                         NASA   (American)        ()  July 20, 1969   
99634   José Antonio Suárez Londoño  (Colombian)    (Male)           1997   

                        Department DateAcquired    URL  ThumbnailURL  \
127075  Prints & Illustrated Books   2015-10-27   True          True   
43467                  Photography   1983-01-13  False         False   
46446                  Photography   1966-04-12   True          True   
127830                 Photography   2016-01-28   True          True   
99634   Prints & Illustrated Books   2009-11-17   True          True   

        Height (cm)  Width (cm)  
127075    18.400000   15.900000  
43467     20.200000   24.700000  
46446     22.600000   16.600000  
127830    19.050038   19.050038  
99634     14.800000    5.000000

## Building a Model

Now, let's see if we can use multi-layer perceptron modeling (or "MLP") to see if we can classify the department a piece should go into using everything but the department name.

Before we import MLP from SKLearn and establish the model we first have to ensure correct typing for our data and do some other cleaning.

In [13]:
# Get data types.
artworks.dtypes

Artist                  object
Nationality             object
Gender                  object
Date                    object
Department              object
DateAcquired    datetime64[ns]
URL                       bool
ThumbnailURL              bool
Height (cm)            float64
Width (cm)             float64
YearAcquired             int64
dtype: object

The `DateAcquired` column is an object. Let's transform that to a datetime object and add a feature for just the year the artwork was acquired.

In [14]:
artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year
artworks['YearAcquired'].dtype

dtype('int64')

Great. Let's do some more miscellaneous cleaning.

In [16]:
artworks.head()

Artist  Nationality    Gender           Date  \
127075                 Rebecca Horn     (German)  (Female)           1998   
43467             Alfred Capel Cure    (British)    (Male)           1856   
46446                   Paul Strand   (American)    (Male)           1916   
127830                         NASA   (American)        ()  July 20, 1969   
99634   José Antonio Suárez Londoño  (Colombian)    (Male)           1997   

                        Department DateAcquired    URL  ThumbnailURL  \
127075  Prints & Illustrated Books   2015-10-27   True          True   
43467                  Photography   1983-01-13  False         False   
46446                  Photography   1966-04-12   True          True   
127830                 Photography   2016-01-28   True          True   
99634   Prints & Illustrated Books   2009-11-17   True          True   

        Height (cm)  Width (cm)  YearAcquired  
127075    18.400000   15.900000          2015  
43467     20.200000   24.700000          1983  
46446     22.600000   16.600000          1966  
127830    19.050038   19.050038          2016  
99634     14.800000    5.000000          2009

In [17]:
# Remove multiple nationalities, genders, and artists.
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

In [24]:
pattern =  re.compile(r'([0-9]{4})')
# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    pattern, expand=False))

In [25]:
artworks.head()

Artist  Nationality    Gender  Date  \
127075                 Rebecca Horn     (German)  (Female)  1998   
43467             Alfred Capel Cure    (British)    (Male)  1856   
46446                   Paul Strand   (American)    (Male)  1916   
127830                         NASA   (American)        ()  1969   
99634   José Antonio Suárez Londoño  (Colombian)    (Male)  1997   

                        Department DateAcquired    URL  ThumbnailURL  \
127075  Prints & Illustrated Books   2015-10-27   True          True   
43467                  Photography   1983-01-13  False         False   
46446                  Photography   1966-04-12   True          True   
127830                 Photography   2016-01-28   True          True   
99634   Prints & Illustrated Books   2009-11-17   True          True   

        Height (cm)  Width (cm)  YearAcquired  
127075    18.400000   15.900000          2015  
43467     20.200000   24.700000          1983  
46446     22.600000   16.600000          1966  
127830    19.050038   19.050038          2016  
99634     14.800000    5.000000          2009

In [26]:
# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat with other variables, but artists slows this wayyyyy down so we'll keep it out for now
X = pd.get_dummies(X, sparse=True)
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

In [32]:
pd.set_option('display.max_columns', 500)
X.head()

URL  ThumbnailURL  Height (cm)  Width (cm)  YearAcquired  Gender_()  \
127075   True          True    18.400000   15.900000          2015          0   
43467   False         False    20.200000   24.700000          1983          0   
46446    True          True    22.600000   16.600000          1966          0   
127830   True          True    19.050038   19.050038          2016          1   
99634    True          True    14.800000    5.000000          2009          0   

        Gender_(Female)  Gender_(Male)  Gender_(male)  \
127075                1              0              0   
43467                 0              1              0   
46446                 0              1              0   
127830                0              0              0   
99634                 0              1              0   

        Gender_\(multiple_persons\)  ()  (Albanian)  (American)  (Argentine)  \
127075                            0   0           0           0            0   
43467                             0   0           0           0            0   
46446                             0   0           0           1            0   
127830                            0   0           0           1            0   
99634                             0   0           0           0            0   

        (Australian)  (Austrian)  (Belgian)  (Bosnian)  (Brazilian)  \
127075             0           0          0          0            0   
43467              0           0          0          0            0   
46446              0           0          0          0            0   
127830             0           0          0          0            0   
99634              0           0          0          0            0   

        (British)  (Cambodian)  (Cameroonian)  (Canadian)  (Chilean)  \
127075          0            0              0           0          0   
43467           1            0              0           0          0   
46446           0            0              0           0          0   
127830          0            0              0           0          0   
99634           0            0              0           0          0   

        (Chinese)  (Colombian)  (Costa Rican)  (Croatian)  (Cuban)  (Czech)  \
127075          0            0              0           0        0        0   
43467           0            0              0           0        0        0   
46446           0            0              0           0        0        0   
127830          0            0              0           0        0        0   
99634           0            1              0           0        0        0   

        (Danish)  (Dutch)  (Egyptian)  (Finnish)  (French)  (German)  \
127075         0        0           0          0         0         1   
43467          0        0           0          0         0         0   
46446          0        0           0          0         0         0   
127830         0        0           0          0         0         0   
99634          0        0           0          0         0         0   

        (Ghanaian)  (Greek)  (Guatemalan)  (Haitian)  (Hungarian)  \
127075           0        0             0          0            0   
43467            0        0             0          0            0   
46446            0        0             0          0            0   
127830           0        0             0          0            0   
99634            0        0             0          0            0   

        (Icelandic)  (Indian)  (Irish)  (Israeli)  (Italian)  (Japanese)  \
127075            0         0        0          0          0           0   
43467             0         0        0          0          0           0   
46446             0         0        0          0          0           0   
127830            0         0        0          0          0           0   
99634             0         0        0          0          0           0   

        (Kenyan)  (Korean)  (Latvian)  (Lebanese)  (Luxembo

In [27]:
# Alright! We've done our prep, let's build the model.
# Neural networks are hugely computationally intensive.
# This may take several minutes to run.

# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 1000 perceptron layer.
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)

/usr/local/lib/python3.7/site-packages/sklearn/utils/__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [28]:
mlp.score(X, Y)

0.5699857074797523

In [29]:
Y.value_counts()/len(Y)

Prints & Illustrated Books    0.523297
Photography                   0.232301
Architecture & Design         0.110243
Drawings                      0.096046
Painting & Sculpture          0.038113
Name: Department, dtype: float64

In [30]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.54164683, 0.53783912, 0.56074321, 0.63757749, 0.31568908])

Now we got a lot of information from all of this. Firstly we can see that the model seems to overfit, though there is still so remaining performance when validated with cross validation. This is a feature of neural networks that aren't given enough data for the number of features present. _Neural networks, in general, like_ a lot _of data_. You may also have noticed something also about neural networks: _they can take a_ long _time to run_. Try increasing the layer size by adding a zero. Feel free to interrupt the kernel if you don't have time...

Also note that we created bools for artist's name but left them out. Both of the above points are the reason for that. It would take much longer to run and it would be much more prone to overfitting.

## Model parameters

Now, before we move on and let you loose with some tasks to work on the model, let's go over the parameters.

We included one parameter: hidden layer size. Remember in the previous lesson, when we talked about layers in a neural network. This tells us how many and how big to make our layers. Pass in a tuple that specifies each layer's size. Our network is 1000 neurons wide and one layer. (100, 4, ) would create a network with two layers, one 100 wide and the other 4.

How many layers to include is determined by two things: computational resources and cross validation searching for convergence. It's generally less than the number of input variables you have.

You can also set an alpha. Neural networks like this use a regularization parameter that penalizes large coefficients just like we discussed in the advanced regression section. Alpha scales that penalty.

Lastly, we'll discuss the activation function. The activation function determines whether the output from an individual perceptron is binary or continuous. By default this is a 'relu', or 'rectified linear unit function' function. In the exercise we went through earlier we used this binary function, but we discussed the _sigmoid_ as a reasonable alternative. The _sigmoid_ (called 'logistic' by SKLearn because it's a 'logistic sigmoid function') allows for continuous variables between 0 and 1, which allows for a more nuanced model. It does come at the cost of increased computational complexity.

If you want to learn more about these, study [activation functions](https://en.wikipedia.org/wiki/Activation_function) and [multilayer perceptrons](https://en.wikipedia.org/wiki/Multilayer_perceptron). The [Deep Learning](http://www.deeplearningbook.org/) book referenced earlier goes into great detail on the linear algebra involved.

You could also just test the models with cross validation. Unless neural networks are your specialty cross validation should be sufficient.

For the other parameters and their defaults, check out the [MLPClassifier documentaiton](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier).

## Drill: Playing with layers

Now it's your turn. Using the space below, experiment with different hidden layer structures. You can try this on a subset of the data to improve runtime. See how things vary. See what seems to matter the most. Feel free to manipulate other parameters as well. It may also be beneficial to do some real feature selection work...

In [34]:
# Your code here. Experiment with hidden layers to build your own model.

mlp_one = MLPClassifier(hidden_layer_sizes=(100,100))
cross_val_score(mlp_one, X, Y, cv=5)

array([0.3750595 , 0.56354117, 0.46212482, 0.61516452, 0.6256557 ])

In [35]:
mlp_two = MLPClassifier(hidden_layer_sizes=(2000,))
cross_val_score(mlp_two, X, Y, cv=5)

array([0.61875297, 0.26511185, 0.56169605, 0.58893658, 0.62756319])

In [37]:
mlp_three = MLPClassifier(hidden_layer_sizes=(200,200))
cross_val_score(mlp_three, X, Y, cv=5)

array([0.57448834, 0.53355545, 0.55788471, 0.4434907 , 0.54840248])

In [38]:
mlp_four = MLPClassifier(hidden_layer_sizes=(200,200,200))
cross_val_score(mlp_four, X, Y, cv=5)

array([0.63350785, 0.62303665, 0.65173892, 0.65140677, 0.59752027])

In [40]:
mlp_five = MLPClassifier(hidden_layer_sizes=(200,200,200), activation ='logistic')
cross_val_score(mlp_five, X, Y, cv=5)

array([0.6592099 , 0.66063779, 0.65173892, 0.65236052, 0.63185503])

In [41]:
mlp_six = MLPClassifier(hidden_layer_sizes=(200,200,200), activation ='logistic', alpha = 0.001)
cross_val_score(mlp_six, X, Y, cv=5)

array([0.66587339, 0.66587339, 0.64459266, 0.66189795, 0.66285169])