In [1]:
import numpy as np

In [3]:
x = np.array([0, 1, 2, 3])
x

In [4]:
w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
y = np.arrange(8).reshape(2,4)
y

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
y = np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
x = np.array([0, 1, 2, 3])

print(np.square(x))

print(np.sqrt(x))

print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [8]:
x = np.array([0, 1, 2, 3])

print(np.max(x))

print(np.min(x))

print(np.mean(x))

print(np.std(x))

3
0
1.5
1.118033988749895
